### ISSUE TITLE
Fix blog

### ISSUE THREAD

**Issue by ibnuda** [jasonstolaruk/CurryMUD#3]
Hello,

I just read one of your [file](https://github.com/jasonstolaruk/CurryMUD/blob/master/lib/Mud/Service/Main.hs#L23) and I want to let you know that the url is updated a while ago to http://ibnuda.gitlab.io/2017-11-03-authorization-in-servant.html

Cheers.

**Comment by jasonstolaruk** [comment]
Thank you!
